name: lami_tag
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  rxdart: ^0.27.7
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  image_picker: ^1.1.1
  firebase_storage: ^12.4.0
  fl_chart: ^0.68.0
  flutter_blue_plus: ^1.32.7
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  flutter_email_sender: ^6.0.3
  google_sign_in: ^6.2.0
  speedometer_chart: ^1.0.8
  url_launcher: ^6.3.1
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/


